apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dev-rbac
  name: dev-rbac
  namespace: rbac-1
spec:
  serviceAccountName: dev
  containers:
  - image: busybox:1.28
    command:
    - sh
    - -c
    - sleep 60000
    name: dev-rbac
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
