apiVersion: v1
kind: Pod
metadata:
  labels:
    run: plain-nginx
  name: plain-nginx
spec:
  containers:
  - image: nginx:1.19.2
    name: plain-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
