---

- hosts: master
  vars:
    kubernetes_version: "1.28"
    kubernetes_patch: "5"
    kubernetes_pkg_rev: "1.1"
    enable_kubernetes_audit: true
    kubernetes_cluster_name: "cluster99"
  become: true
  roles:
    - role: kube-base
    - role: kube-master
    - role: local-pv-provisioner
