---
# tasks file for task preparation

- name: Perform task setup
  ansible.builtin.meta: noop

- name: Make sure /var/work exists
  file:
    path: /var/work
    owner: root
    group: root
    state: directory
  
- name: Copy task-setup.yaml to remote
  copy:
    content: "{{ lookup('template', 'profile-nginx.json') }}"
    owner: root
    group: root
    mode: 0640
    dest: /var/work/profile-nginx.json
