---
# tasks file for task preparation

- name: Install etcd tools
  shell: "{{ lookup('template', 'install-etcd-tools.sh') }}"
  args:
    executable: /bin/bash
  register: ebgn
  changed_when: "'etcd tools installed' in ebgn.stdout"

- name: Copy task-setup.yaml to remote
  copy:
    content: "{{ lookup('template', 'task-setup.yaml') }}"
    owner: root
    group: root
    mode: 0640
    dest: "{{ task_setup_yaml_path }}"

- name: Perform task setup
  shell: "{{ lookup('template', 'setup.sh') }}"
  args:
    executable: /bin/bash
  register: kbgn
  changed_when: "'Setup completed' in kbgn.stdout"
