apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: db-admin
  name: db-admin
  namespace: team-5
spec:
  containers:
  - image: busybox:1.28
    command:
    - sh
    - -c
    - sleep 60000
    name: db-admin
    volumeMounts:
      # name must match the volume name below
      - name: secret-volume
        mountPath: /mnt/secret
        readOnly: true
    resources: {}
  volumes:
    - name: secret-volume
      secret:
        secretName: db-admin
  dnsPolicy: ClusterFirst
  restartPolicy: Always
