# https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3#ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
clusterName: "{{ kubernetes_cluster_name | default('kubernetes') }}"
controlPlaneEndpoint: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}:6443"

kubernetesVersion: v{{ kubernetes_version }}.{{ kubernetes_patch }}
apiServer:
  certSANs:
  - "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
{% if enable_kubernetes_audit == true %}
  extraVolumes:
    - name: "k8s-aduit-log-dir"
      hostPath: "{{ kubernetes_audit_log_dir }}"
      mountPath: "{{ kubernetes_audit_log_dir }}"
      readOnly: false
      pathType: DirectoryOrCreate
    - name: "k8s-aduit-conf-dir"
      hostPath: "{{ kubernetes_audit_conf_dir }}"
      mountPath: "{{ kubernetes_audit_conf_dir }}"
      readOnly: false
      pathType: DirectoryOrCreate
{% endif %}
  extraArgs:
    enable-admission-plugins: "{% for plugin in admission_plugins %}{{ plugin }}{% if not loop.last %},{% endif %}{% endfor %}"
    advertise-address: "{{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
    profiling: "{{ kubernetes_apiserver_profiling }}"
{% if enable_kubernetes_audit == true %}
    audit-policy-file: "{{ kubernetes_audit_conf_dir }}/{{ kubernetes_audit_policy_file }}"
    audit-log-path: "{{ kubernetes_audit_log_dir }}/{{ kubernetes_audit_log_file }}"
    audit-log-maxage: "{{ kubernetes_audit_log_max_age }}"
    audit-log-maxsize: "{{ kubernetes_audit_log_max_size }}"
    audit-log-maxbackup: "{{ kubernetes_audit_log_max_backup }}"
{% endif %}
controllerManager:
  extraArgs:
    profiling: "{{ kubernetes_controller_manager_profiling }}"
scheduler:
  extraArgs:
    profiling: "{{ kubernetes_scheduler_profiling }}"
networking:
  podSubnet: "{{ pod_cidr }}"
