apiVersion: v1
kind: Pod
metadata:
  labels:
    run: untrusted
  name: untrusted
spec:
  containers:
  - image: quay.io/quay/busybox@sha256:92f3298bf80a1ba949140d77987f5de081f010337880cd771f7e7fc928f8c74d
    name: untrusted
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
