apiVersion: v1
kind: Pod
metadata:
  labels:
    run: box1
  name: box1
  namespace: sa-verify
spec:
  volumes:
  - name: db-secret-vol
    secret:
      secretName: database-access
  containers:
  - image: nginx:1.19.2
    name: box1
    resources: {}
    volumeMounts:
      - name: db-secret-vol
        readOnly: true
        mountPath: "/etc/secret-volume"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
